spring:
  cloud:
    gateway:
      routes:
        - id: pcb_spring
          uri: lb://pcb-spring/
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: baidu
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
